---
- name: Installation and configuration of apache2
  hosts: all
  become: yes
  tasks:
    - name: install apache2 server
      yum: 
        name: httpd
        update_cache: true
        state: present
    - name: start apache2 service
      service:
        name: httpd
        state: started
    - name: set server1 timezone
      community.general.timezone:
        name: Africa/Lagos
    - name: display my hostname
      shell: echo "<h1>This is $(hostname -f) and the date is $(date) </h1>" >> /var/www/html/index.html
    - name: restart apache2 service
      service:
        name: httpd
        state: restarted
